### ISSUE TITLE
banner function throws error

### ISSUE THREAD

**Issue by dsavransky** [lstagner/idl_kernel#1]
After initial install, I could not get this to run - anytime it tried to create a kernel (with any interface - console or notebook) it'd error out with: 

 `Command '['/bin/idl', '-e "" ']' returned non-zero exit status 1`

If I run idl -e "" from the command line I get the usual version info and output from my startup file (same results when I unset the startup file environment dir).  I hardcoded the banner function to just return the version string and after that it launched with zero issues.

I'm running IDL 8.4 on Mac OS X 10.10.3, python 2.7.9, ipython 3.1.0.  No other issues, except I can't get color on inline plots.

Thanks for a cool project.

**Comment by lstagner** [comment]
Hmm...I have no idea why it doesn't work for you. It may be a mac thing. A better work around is to default to no banner when an error occurs. Try replacing the banner function with this

``` python
    def banner(self):
        if self._banner is None:
            try:
                if os.path.basename(self._executable) == 'idl':
                    self._banner = check_output([self._executable, '-e "" ']).decode('utf-8')
                else:
                    self._banner = check_output([self._executable, '--version']).decode('utf-8')
            except:
                self._banner = ""
        return self._banner
```

As for the colors on the inline plots you may have to mess around with your device settings. In my startup file I have

``` idl
DEVICE, true_color=24, decomposed=0
DEVICE, retain=2
```

That may work for you.

**Comment by dsavransky** [comment]
Thanks for the response.  Possibly a mac thing - but weirdly, it looks like the -e argument is being rejected in subprocess:

```
In [23]: process = Popen([self._executable, '-e " " '])
In [24]: idl: -e " "  option not recognized.
```

When run from the command line, the behavior is exactly as expected.

**Comment by lstagner** [comment]
Try this

``` python
process = Popen([self._executable,  '-e', ' " " '])
```

or

``` python
self._banner = check_output([self._executable, '-e', ' "" ']).decode('utf-8')
```

**Comment by dsavransky** [comment]
It seems like the double quotes are (inexplicably) what's giving it trouble.  However,
`self._banner = check_output([self._executable, '-e', '']).decode('utf-8')`
works.  Not sure whether it'll work on all OSses/IDL versions though.  Another possibility might be: 
`self._banner = check_output([self._executable, '-e', 'print,!version.release'])`

Thanks.

**Comment by lstagner** [comment]
Neither those options work for me. This however does

 `self._banner = check_output([self._executable,'-e','"print,string(0B)"'])`

Does this work on your Mac?

**Comment by dsavransky** [comment]
Nope - it still has a problem with the double quotes in the argument (they're not stripped off, so IDL errors on the command.  

The problem appears to be a fundamental difference between how Popen parses string arguments on Windows and posix systems (https://docs.python.org/2/library/subprocess.html).  I think the path of least resistance is probably something like:

```
if os.name is 'posix':
     self._banner = check_output([self._executable, '-e', '']).decode('utf-8')
else:
     self._banner = check_output([self._executable, '-e', ' "" ']).decode('utf-8')
```

I think any other solution would require setting shell=True which is strongly discouraged.

**Comment by lstagner** [comment]
Nope...That wont work because linux is also `'posix'` and an empty string doesn't work for me. The banner is really only used to get the IDL version and that is not so important. I will just have it try to get the banner and have it fail gracefully if it can't.
